### ISSUE TITLE
SourceComments output stdin instead of filename

### ISSUE THREAD

**Issue by Cammisuli** [webpack-contrib/sass-loader#202]
Hi there, 

When using sass-loader and setting sourceComments to true, the outputted css always shows "stdin" as the filename rather than the actual file.

Here's my config for the loader:

``` javascript
{
    test: /\.scss$/,
    exclude: /node_modules/,
    loader: ExtractTextPlugin.extract('style-loader', "css!sass?sourceComments")
}
```

sample scss file (www/component/component.scss):

``` scss
$color: purple;
h2{
    color: $color;
}

h3{
    padding: 10px;
}

div {
    margin: 20px;
    p{
        padding: 20px;
    }
}
```

css output (component.css):

``` css
/* line 2, stdin */
h2 {
  color: purple; }

/* line 6, stdin */
h3 {
  padding: 10px; }

/* line 10, stdin */
div {
  margin: 20px; }
  /* line 12, stdin */
  div p {
    padding: 20px; }
```

Is there a way to have the proper file name in the comment, rather than stdin? Thanks!
