### ISSUE TITLE
@imports variables unicode character, keep It ?

### ISSUE THREAD

**Issue by noyobo** [webpack-contrib/sass-loader#294]
## Bad case

variable.scss

``` sass
$hello: '\e601';
```

index.scss

``` sass
@import './variable.scss';

.a {
  content: $hello;
}
```

After webpack + sass-loader compiled output：

index.css

``` css
@charset "UTF-8";
.a {
  content: ""; }

```
## not use `@import`

index.scss

``` scss
// @import './variable.scss';

.a {
  // content: $hello;
  content: '\e601';
}
```

output:

index.css

``` css
.a {
  content: '\e601'; }
```

How can i keep unicode by import variable ?

webpack.config.js

``` js
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin')

var extractCSS = new ExtractTextPlugin('[name].css');

module.exports = {
  context: process.cwd(),
  "entry": {
    index: './src/index.js'
  },
  "output": {
    "path": "./build",
    "filename": "[name].js",
    "chunkFilename": "[name].js"
  },
  "resolve": {
    "extensions": [
      "",
      ".js",
      ".jsx"
    ]
  },
  module: {
    loaders: [{
      test: /\.js$/,
      loader: "babel",
      query: {
        presets: [
          'es2015',
          'stage-0',
        ]
      }
    }, {
      test: /\.scss$/,
      loader: extractCSS.extract(['css', 'sass'])
    }],
  },
  plugins: [
    extractCSS
  ]
}

```
