### ISSUE TITLE
Possible issue with single quotes in sass

### ISSUE THREAD

**Issue by karptonite** [webpack-contrib/sass-loader#354]
I'm uncertain which of the loaders (or plugin) in this chain is at fault, but I have a working example of a webpack config that fails to compile stylesheets properly when, in some cases, single quotes are included in the sass.
Here is a repo that can be used to reproduce this issue:

https://github.com/karptonite/angular2-webpack-starter

The relevant part of the webpack config is here:
https://github.com/karptonite/angular2-webpack-starter/blob/master/config/webpack.prod.js#L101-L111

This is a particularly frustrating bug because the failure takes the form of reporting an error in an entirely different part of the scss code, but you'll find that it compiles fine if you replace the single quotes in this file with double quotes:
https://github.com/karptonite/angular2-webpack-starter/blob/master/src/styles/pages/_test.scss#L3

I apologize if this is an issue with a different loader (or the ExtractText Plugin)--I wasn't able to nail down exactly which loader was at fault. If it seems that a different loader is causing the problem, let me know and i'll report this in the correct repo.

Note that the Readme for the repo includes the steps to reproduce the bug!

**Comment by evilebottnawi** [comment]
@karptonite Can your update `webpack`, `sass-loader` and other related packages to `webpack` to latest version and try again. If the error persists, report this here :+1:

**Comment by karptonite** [comment]
So while I can't replicate the error exactly, i can replicate it sort of. Here is an example:
https://github.com/karptonite/angular2-webpack-starter/tree/updated-example

It now seems to be the case that ANY quotes (single or double) in a sass mixin are a problem, but only when resolve-url-loader is part of the chain.
https://github.com/karptonite/angular2-webpack-starter/commit/afb24c1933669d5e62aac608f839c9d75b4c0cb8

Sorry I didn't have time to nail this down further, but if you check out the `updated-example` branch of that repo and follow the instructions in the README, you should see the error.

I am no longer using webpack directly--I switched to angular-cli, but this was a frustrating issue, so I want to help make sure it doesn't hit anyone else!

**Comment by evilebottnawi** [comment]
@karptonite let's do it :+1: thanks for repo

**Comment by evilebottnawi** [comment]
@karptonite latest `node-sass` and `libSass` compile
```scss
.game-header-image {
	@include media-breakpoint-down(sm) {
		content: '';
	}
}
```
to
```scss
@media (max-width: breakpoint-max(sm, (xs: 0, sm: 576px, md: 768px, lg: 992px, xl: 1200px))) {
  .game-header-image {
    content: '';
  }
}
```

`sass` v4 latest output error on this
```shell
(xs: 0, sm: 576px, md: 768px, lg: 992px, xl: 1200px) isn't a valid CSS value.
```

`sass` v3 latest output nothing on this

**Comment by evilebottnawi** [comment]
@karptonite bug in `rework` in `resolve-url-loader` (parser). Seems `rework` is outdate today and best is use `postcss` for this purpose.

Minimal code to reproduce:
```scss
@import "~bootstrap/scss/variables";
@import "~bootstrap/scss/mixins";
@import "~bootstrap/scss/navbar";

.game-header-image {
	@include media-breakpoint-down(sm) {
		content: '';
	}
}
```

Simple: `rework` don't add `}` to some block (`declaration block`).

I created issue in `resolve-url-loader` and close issue here, because this issue not related to `sass-loader`.

Related issue: https://github.com/bholloway/resolve-url-loader/issues/56.

Thanks for helping to do `webpack` better!
