### ISSUE TITLE
String interpolation in @each

### ISSUE THREAD

**Issue by BHouwens** [webpack-contrib/sass-loader#427]
When trying to use Sass's `@each` directive with string interpolation of the loop variables I get an unknown word error.

The following example code:
```scss
$sizes: (
  "small": 12px, 
  "large": 14px
);

@each $name, $size in $sizes {
  .#{$name} {
    font-size: $size;
  }
}
```

results in the following build error:

```
Module build failed: Unknown word (75:6)

  73 |
  74 | @each $name, $size in $sizes {
> 75 |   .#{$name} {
     |      ^
```
