### ISSUE TITLE
@imports not working

### ISSUE THREAD

**Issue by danieladonna** [webpack-contrib/sass-loader#433]
Hello, 

i tried a lot of different configurations but the compilaton of all the included scss files still fails.
The imports are just completely removed from the scss.

My webpack.config
```js
const path = require('path');
const BrowserSyncPlugin = require('browser-sync-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const ExtractTextPlugin = require("extract-text-webpack-plugin");

module.exports = {
  entry: './app/index.ts',
	context: path.join(__dirname, 'src'),
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist')
  },
	module: {
  	rules: [
			{
        test: /\.exec\.js$/,
        use: [ 'script-loader' ]
      },
			{
				test: /\.tsx?$/,
				loader: 'ts-loader',
				exclude: /node_modules/,
			},
			 {
    test: /\.scss$/,
    loader: ExtractTextPlugin.extract({
      fallback: 'style-loader',
      loader: [
        {
          loader: 'css-loader',
          options: {
            sourceMap: true,
            minimize: true,
            discardComments: {
              removeAll: true
            }
          }
        },
        {
          loader: 'postcss-loader',
					options: {
              plugins: function () {
                return [
                  require('postcss-import'),
                  require('autoprefixer')
                ];
              }
					}
        },
        {
          loader: 'sass-loader',
          options: {
            sourceMap: true
          }
        }
      ]
    })
  }
   ]
	},
	plugins: [
		new ExtractTextPlugin("styles.css"),
		new CopyWebpackPlugin([
			{ 
				from: '**/*'
			},
		], {
			ignore: [
				'style/**',
				'app/**'
			]
		}),
    new BrowserSyncPlugin({
      host: 'localhost',
      port: 3000,
      server: { baseDir: ['dist'] }
    })
  ]
};
```

My style.scss
```scss
@import "./settings.scss";
@import "~foundation-sites/scss/foundation";

body {
	font-family: 'Roboto', sans-serif;
}

h1 {
	color: green;
	font-family: 'Roboto', sans-serif;
}
```

The result:
```css
body,h1{font-family:Roboto,sans-serif}h1{color:green}
```

There is no error in the console and if i change the path of foundation i get an error. So the paths seems to be correct, but the imports are not written to the bundled css file.

What am i doing wrong? 

Thanks a lot.

D
