### ISSUE TITLE
String interpolation broken?

### ISSUE THREAD

**Issue by alexandernanberg** [webpack-contrib/sass-loader#443]
I can't string interpolation to work with the sass-loader. Works without any problems on node-sass. Bug or missing feature? Would be awesome if it got fixed/implemented.

```scss
.someclassname-#{'interpolated'} {
  display: flex;
}
```
Throws this error: `module build failed: Unknown word (19:19)`
