### ISSUE TITLE
Deep nesting with a variable causes build fail

### ISSUE THREAD

**Issue by subhaze** [webpack-contrib/sass-loader#502]
I ran into an issue where builds would fail when using variables that were deeply nested, though, I'm not sure if this is specifically a sass-loader issue.

I pulled the code and modified https://github.com/webpack-contrib/sass-loader/blob/master/lib/loader.js#L15 to use the `sass.renderSync` function which appears to remedy the issue.

The minimal amount of breaking code I've come up with is the following:

fails
```scss
$testing: #ff00ff;
body{
  div{
    div{
      div{
        div{
          div{
            div{
              div{
                div{
                  div{
                    div{
                      div{
                        &.a-class{
                          span{
                            color: $testing;
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

Yeah... lots of nesting... but when a variable is used at that level webpack fails to build.

However, if you comment out one of the divs, OR, if you use the color `#ff00ff` directly the build does not fail.

works
```scss
$testing: #ff00ff;
body{
  div{
    div{
      div{
        div{
          div{
            div{
              div{
                div{
                  div{
                    div{
                      // div{
                        &.a-class{
                          span{
                            color: $testing;
                          }
                        }
                      // }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

works
```scss
$testing: #ff00ff;
body{
  div{
    div{
      div{
        div{
          div{
            div{
              div{
                div{
                  div{
                    div{
                      div{
                        &.a-class{
                          span{
                            color: #ff00ff;
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```
