### ISSUE TITLE
Error: Missing whitespace after :global

### ISSUE THREAD

**Issue by chacbumbum** [webpack-contrib/sass-loader#507]
This is my style:

Error
```scss
.wrap-box {
    margin: 15px 0;
    :global {
        &.box {
            .otherClass {
                width: 44px;
                height: 44px;
                display: flex;
                justify-content: center;
                align-items: center;
                font-size: 20px;
            }
        }
    }
}
```
Error message
>Module build failed: Missing whitespace after :global (3:3)

How can I fix this issue.

Sorry if the issue is already there but I can not find it.

Thanks!

**Comment by evilebottnawi** [comment]
@chacbumbum can you provide config or minimum reproducible test repo?

**Comment by chacbumbum** [comment]
I use create-react-app.
This is config in `webpack.config.dev.js`
```javascript
....
                   {
                        test: /\.s[ac]ss$/,
                        use: [
                            require.resolve('style-loader'),
                            {
                                loader: require.resolve('css-loader'),
                                options: {
                                    importLoaders: 2,
                                    camelCase: true,
                                    modules: true
                                }
                            },
                            {
                                loader: require.resolve('sass-loader'),
                                options: {
                                    includePaths: [paths.appSrc]
                                }
                            }
                        ]
                    },
```

**Comment by evilebottnawi** [comment]
@chacbumbum can you try escape `\:global`? I am not familiar with css modules

**Comment by chacbumbum** [comment]
@evilebottnawi There is no error notification anymore while created style is incorrect

**Comment by michael-ciniawsky** [comment]
@chacbumbum Please show the incorrect styles (output), nesting inside `:global` might be a problem

**Comment by chacbumbum** [comment]
@michael-ciniawsky  I want integration with css-loader and enable modules options [https://github.com/webpack-contrib/css-loader#modules](https://github.com/webpack-contrib/css-loader#modules)

**Comment by michael-ciniawsky** [comment]
Yep sure, but `sass-loader` (nesting) runs before `css-loader` (CSS Modules), so maybe the sass compiler messes up on `:global` (unknown in `sass`) + nesting (incorrect styles). I need the actual output to verify :)

**Comment by chacbumbum** [comment]
I want complier from
```javascript
.wrap {
    :global {
        &.original-class {
        // style
        }
    }
}
```
to
```javascript
._2_aKvs-b8bW2Vg3fwHozO.original-class {
  // style
}
```

**Comment by JounQin** [comment]
@evilebottnawi Here is a reproduction, please help to locale this issue.

**Comment by evilebottnawi** [comment]
@chacbumbum @JounQin problem not located in `sass-loader`, it is bug in `postcss-modules-local-by-default` which use into `css-loader`, i recomend use `postcss` plugin for `postcss-loader` (https://github.com/css-modules/postcss-modules). Also in `css-loader` we remove support `css-modules` in favor `postcss` plugin. Thank for issue!

**Comment by JounQin** [comment]
@evilebottnawi Any reference about the issue related to `postcss-modules-local-by-default`?

**Comment by evilebottnawi** [comment]
@JounQin should be fixed in `postcss-modules-local-by-default@2`, but in `css-loader` we use `1` version, simple solution move to `postcss-plugin` and disable modules in  `css-loader`

**Comment by JounQin** [comment]
@evilebottnawi But I have not enabled `modules` option in `css-loader`, and I tried to add `postcss-loader` + `postcss-modules` but it still did not work. So maybe that's a unsupported syntax yet for css-modules?

**Comment by evilebottnawi** [comment]
@JounQin hm, should be, i investigate this in near future

**Comment by asumaran** [comment]
any workaround?

I've created my React app with `create-react-app` `v3.0.1` and I'm trying to use CSS modules.

I want to make the following CSS:

```scss
.foo {
  :global {
    &.ant-select {
      width: 105px;
    }
  }
}
```

which I think it should output

```css
.styles_foo__3BRjd.ant-select {
  width: 105px;
}
```
