### ISSUE TITLE
Environment variables not override third variables module

### ISSUE THREAD

**Issue by jianghai** [webpack-contrib/sass-loader#631]
```js
// webpack config
{
    loader: 'sass-loader',
    options: {
        data: '$color: orange;'
    }
}
```

```scss
@import '~some-third-variables'; // which $color: blue;

.title {
  color: $color;
}
```

Result: title color is blue
Expect: title color is orange

🙏
