### ISSUE TITLE
does not import css for modules

### ISSUE THREAD

**Issue by isum** [webpack-contrib/sass-loader#675]
* Operating System: linux
* Node Version: v11.12.0
* NPM Version: 6.9.0
* webpack Version: 4.29.6
* sass-loader Version: 7.1.0

### Expected Behavior

When importing sass file like: `import scssDict from './index.scss';`
with `{loader: 'css-loader', options: {modules: true`
The variable scssDict should contain dictionary with all class names, including files that are imported within.

### Actual Behavior

The dictionary does not contain classes, imported within, from css file and works fine with scss.

```scss
// index.scss
@import "index.css"; // dictionary does not contain classes from this file!
@import "another.scss"; // works ok
.im-from-scss {
  bottom: 20px;
}
```

### Code

[bug-repo.zip](https://github.com/webpack-contrib/sass-loader/files/3046777/bug-repo.zip)

### How Do We Reproduce?

```js
npm run build
```
load build/index.html and see console output
