### ISSUE TITLE
sass-loader ignores import-only files

### ISSUE THREAD

**Issue by jathak** [webpack-contrib/sass-loader#788]
- Operating System: Debian Stretch
- Node Version: 13.5.0
- NPM Version: 6.13.4
- webpack Version: 4.41.5
- sass-loader Version: 8.0.0
- Sass version: Dart Sass 1.24.1

### Expected Behavior

`@import` rules should load the [import-only file](https://sass-lang.com/documentation/at-rules/import#import-only-files) if one exists, instead of the regular file (as is the case for `@use` and `@forward` rules).

This behavior is necessary to allow for incremental migration to the Sass module system, as libraries use import-only files to preserve manual member prefixes for `@import` users while removing them for users who migrate to the module system.

### Actual Behavior

`@import` rules always load the regular file, even if an import-only file exists. The code below works with Dart Sass on its own, but errors when run through sass-loader.

### Code

```scss
// style.scss
@import "dependency";

a {
  color: $dep-color;
}

// _dependency.scss
$color: blue;

// _dependency.import.scss
@forward "dependency" as dep-*;
```
