### ISSUE TITLE
sass-loader@8.0.0 can't use  /deep/  in vue-cli4 scss style

### ISSUE THREAD

**Issue by BobsLi** [webpack-contrib/sass-loader#789]
[  https://github.com/BobsLi/my-issues/tree/master/sassLoaderv8-test
](  https://github.com/BobsLi/my-issues/tree/master/sassLoaderv8-test

- Operating System: win10
- Node Version: v10.16.3
- NPM Version: v6.9.0
- webpack Version:  ^4.0.0
- sass-loader Version: v8.0.0

### Expected Behavior

/deep/  .test  OR ::v-deep .test can use

### Actual Behavior

/deep/  .test can use
::v-deep .test can't use, SassError: expected selector.

### Code
```scss
<style lang="scss" scoped>
.scroll-container {
  white-space: nowrap;
  position: relative;
  overflow: hidden;
  width: 100%;
  ::v-deep .el-scrollbar__bar {
    bottom: 0px;
  }
  /deep/ .el-scrollbar__wrap {
    height: 49px;
  }
}
</style>
```
