### ISSUE TITLE
Export interface to modify scss content after getting all `@import` scss module and before compiling with `node-sass` or `sass` 

### ISSUE THREAD

**Issue by purple-force** [webpack-contrib/sass-loader#812]
### Feature Proposal
Export interface to modify scss content after getting all `@import` scss module and before compiling with `node-sass` or `sass` 
### Feature Use Case
`a.scss`:
```scss
$color: #838383;
div {
  color: $color;
}
```

`b.scss`:
```scss
@import './a.scss';
$font-size: 14px;
p {
  font-size: $font-size;
}
```

Expected output is as below after modifying:

```scss
$color: #838383;
div {
  color: var(--color, $color);
}
$font-size: 14px;
p {
  font-size: var(--font-size, $font-size);
}
```
