### ISSUE TITLE
Issue with factoring out coefficient from calc

### ISSUE THREAD

**Issue by hosseinamin** [webpack-contrib/sass-loader#850]
- Operating System: Linux
- Node Version: v12.8.1
- NPM Version: v6.10.2
- webpack Version: 4.43.0
- sass-loader Version: 8.0.2

### Expected Behavior

``` css
.b4x {
  width: calc(4 * (var(--block-width) + var(--block-margin)));
}
```

### Actual Behavior

``` css
.b4x {
  width: calc(var(--block-width) + var(--block-margin));
}
```

### Workaround

Factor out the coefficient manually.
```
.b4x {
  width: calc(4 * (var(--block-width) + var(--block-margin)));
}
``` 

### How Do We Reproduce?

using `vuepress@1.4.1` .

The converted css of the following is not right. But I've checked with `node-sass` the issue is not is sass. Instead it is in some kind of minifier or something when you build the vuepress. Not as client mode..

Here's the project I found the issue in, https://github.com/AceCentre/SpeakBook/

https://github.com/sass/sass/issues/2868

``` scss
.b4x {
  width: calc(var(--block-width) * 4 + var(--block-margin) * 4);
}
```

I've created this issue in two other places. Learn more about it in there too.
https://github.com/vuejs/vuepress/issues/2433
https://github.com/sass/sass/issues/2868
