### ISSUE TITLE
Using @at-root inside grouped selector

### ISSUE THREAD

**Issue by prbxr** [webpack-contrib/sass-loader#903]
os: all oss
node: 12.19
npm: 6.14.8
sass-loader: 10.1.0
webpack: 4.42.2
preact: 10.5.4

It is a css modules file
```scss
@mixin ROOT($selector) {
    @at-root #{$selector}#{&} {
        @content;
    }
}


[data-role='root-ui'] {
    .button {
        &.secondary,
        &.primary {
            height: 31px;
            @include ROOT('[data-mq-landscape]') {
                height: 24px;
            }
        }
    }
}
```

It is EXPECTED that the generated css  will affect secondary and primary equally.
ACTUALLY css doesn't add @at-root [data-mq-landscape] for the primary class.
Meaning the secondary is 31px height, but primary is 24px height, though root element does not have the [data-mq-landscape] .

Something like:

Actual:
```css
[data-role='root-ui'][data-mq-landscape] .button .secondary, [data-role='root-ui'] .button .primary {
   height: 24px;
}
```
Expected:
```css
[data-role='root-ui'][data-mq-landscape] .button .secondary, [data-role='root-ui'][data-mq-landscape] .button .primary {
   height: 24px;
}
```

If exchaning primary and secondary places, then the problem happens to the secondary.
So the problem is with the second class after the comma.
