### ISSUE TITLE
"additionaldata"  does not work on modules imported by @use

### ISSUE THREAD

**Issue by curlykay** [webpack-contrib/sass-loader#909]
- Operating System:macos 10.14.6
- Node Version:12.18.1
- NPM Version:6.14.5
- webpack Version:4.44.2
- sass-loader Version:10.1.0

I'm not sure whether it's a design specification or a mistake, but it really bothers me.

### Expected Behavior

I hope I can use the global variables added by additionaldata in the module imported by @ use

### Actual Behavior

```
// error
Syntax Error: SassError: Undefined variable.
  ╷
2 │ $text:$content + " 2021";
  │       ^^^^^^^^
  ╵
  src/styles/variables.scss 2:7  @use
  src/App.vue 13:1               root stylesheet
```

### Code

```js
// vue.config.js
module.exports = {
  css: {
    loaderOptions: {
      sass: {
        implementation: require("sass")
      },
      scss: {
        additionalData: '$content:"hello world";'
      }
    }
  }
};
```
```scss
//variables.scss
$text:$content + " 2021";
```

```vue
//App.vue
<template>
  <div id="app"></div>
</template>

<script>
export default {
  name: "App"
};
</script>

<style lang="scss">
@use "~@/styles/variables.scss" as vars;
// // @import is ok but i want to use @use
// @import "~@/styles/variables.scss";

#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
  &::before {
    content: vars.$text;
  }
  // &::before {
  //   content: $text;
  // }
}
</style>

```

### How Do We Reproduce?

You can see the error by executing these commands

```bash
# this is a simplified example
git clone https://github.com/curlykay/sass-use.git
cd sass-use
npm i
npm run serve
```

**Comment by alexander-akait** [comment]
Yes, it is limitation, `additionalData` works only on entry file, i.e.:
```scss
$content:"hello world";
@use "~@/styles/variables.scss" as vars;
// // @import is ok but i want to use @use
// @import "~@/styles/variables.scss";

#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
  &::before {
    content: vars.$text;
  }
  // &::before {
  //   content: $text;
  // }
}
```

And can't be fixed due limitation on `sass` side, you can use workaround:
```
// vue.config.js
module.exports = {
  css: {
    loaderOptions: {
      sass: {
        implementation: require("sass")
      },
      scss: {
        additionalData: '@use 'path/to/variables' as myVars;'
      }
    }
  }
};
```

Other solution is using `https://github.com/sass/node-sass#functions--v300---experimental` and write own function to get values, sorry

This option will be removed in the next releases, due limitations and problems with source maps
