### ISSUE TITLE
additionalData option does not work

### ISSUE THREAD

**Issue by IvanSavoskin** [webpack-contrib/sass-loader#934]
- Operating System: macOS 11.2.3
- Node Version: v14.15.3
- NPM Version: 7.6.3
- webpack Version: 5.24.4
- sass-loader Version: 11.0.1

### Expected Behavior

Adding an import line to a specific .scss file using the additionalData option

### Actual Behavior

The line is not added, the file remains exactly the same as it was

### Code

Trying to add imports with just a line
```js
// webpack.config.js
module: {
        rules: [{
            test: /\.scss$/,
            include: [PATHS.global],
            use: ["style-loader", "css-loader", "sass-loader"]
        }, {
            test: /\.scss$/,
            include: [PATHS.variables],
            use:
                ["style-loader", "css-loader", {
                    loader: "sass-loader",
                    options: {
                        additionalData: `@import "src/styles/themes/${theme}Theme.scss";`
                    }
                }]
        }, {
            test: /\.scss$/,
            exclude: [/node_modules/, PATHS.global, PATHS.variables],
            use: [
                "style-loader", {
                    loader: "css-loader",
                    options: {
                        import: true,
                        sourceMap: true,
                        modules: {
                            mode: "local",
                            localIdentName: "[path][name]__[local]--[hash]",
                            exportLocalsConvention: "camelCase"
                        }
                    }
                }, {
                    loader: "postcss-loader",
                    options: {
                        sourceMap: true,
                        postcssOptions: {
                            config: path.resolve(__dirname, "postcss.config.js")
                        }
                    }
                }, {
                    loader: "sass-loader",
                    options: {
                        sourceMap: true
                    }
                }
            ]
        },
        ...
        ]
    }
```

Trying to add imports using a function
```js
// webpack.config.js
module: {
        ...
        {
            test: /\.scss$/,
            include: [PATHS.variables],
            use:
                ["style-loader", "css-loader", {
                    loader: "sass-loader",
                    options: {
                        additionalData: (content: string) => `@import "src/styles/themes/${theme}Theme.scss";\n${content}`
                    }
                }]
        }
        ...
     ]
    }
```

The file where you want to add the import
```scss
// variables.scss
$header-height: 50px;
$ext-line-height: 45px;
$editor-tabs-height: 30px;
$wizard-action-height: 65px;
$app-height: calc(100vh - #{$header-height});
$content-height: calc(#{$app-height} - #{2*$ext-line-height});
$wizard-height: $app-height;
$wizard-content-height: calc(#{$wizard-height} - #{$wizard-action-height});
```
