### ISSUE TITLE
Output differ when using `@use` rule instead of `@import`

### ISSUE THREAD

**Issue by xavierfoucrier** [webpack-contrib/sass-loader#936]
I am currently migrating one of my project to use the new sass `@use` rule, as suggested [in the official documentation](https://sass-lang.com/documentation/at-rules/use), and remove the old `@import` one. This project uses `PurgeCSS` to remove unused classes from the output, really useful to reduce bundle size.

The fact is that, when using `@use`, the output differs.

For example, this code:
```scss
/*! purgecss start ignore */
@import 'component/a';
.b { color: grey; }
/*! purgecss end ignore */
```

Was previously producing:
```css
/*! purgecss start ignore */
.a { color: red; }
.b { color: grey; } 
/*! purgecss end ignore */
```

But now, if I switch to `@use` rule, the same code give a different build result:
```scss
/*! purgecss start ignore */
@use 'component/a';
.b { color: grey; }
/*! purgecss end ignore */
```

```css
.a { color: red; }
/*! purgecss start ignore */
.b { color: grey; }
/*! purgecss end ignore */
```

Making the component `a` to be purged, as comments moved... when he shouldn't.

I fully understand than using `@use` will make the sass works as "modules", but what I don't understand is why the comments that are placed in a specific order are not preserved.

Thanks a lot for further explanation :wink: 

Here are some additional informations about my setup:
- Operating System: Windows 7 x64
- Node Version: 13.14.0
- NPM Version: 6.14.9
- webpack Version: 5.30.0
- sass-loader Version: 11.0.1

> I am not sure if this is related to `sass-loader` or `sass` (dart) itself... :thinking:
