### ISSUE TITLE
Exporting scss variables into js doesn't work anymore

### ISSUE THREAD

**Issue by florianrubel** [webpack-contrib/sass-loader#951]
```scss
:export {
    colorPrimary: $color-primary;
    colorSecondary: $color-secondary;
    colorSecondaryTransparent: $color-secondary-transparent;

    spacing: $spacing;

    appHeaderHeight: $app-header-height;

    profilePictureSizeSmall: $profile-picture-size-small
}
```

`import scssVariables from '@/scss/01_base/_variables.scss';`

scssVariables contains an empty object.
